import NewTodoZ from "@/components/zustand/NewTodo";
import NewTodoJ from "@/components/jotai/NewTodo";
import TodoListZ from "@/components/zustand/TodoList";
import TodoListJ from "@/components/jotai/TodoList";
import Head from "next/head";
import NewTodoAtom from "@/components/jotai/NewTodoAtom";
import TodoAtomList from "@/components/jotai/TodoAtomList";
import NewTodoV from "@/components/valtio/NewTodo";
import TodoListV from "@/components/valtio/TodoList";
import TodoListOpt from "@/components/valtio/TodoListOpt";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3>Zustand</h3>
        <NewTodoZ></NewTodoZ>
        <TodoListZ></TodoListZ>
        <br />
        <br />
        <br />
        <h3>jotai</h3>
        <NewTodoJ></NewTodoJ>
        <TodoListJ></TodoListJ>
        <br />
        <br />
        <br />
        <h3>jotai (Atoms in Atom 패턴)</h3>
        <NewTodoAtom></NewTodoAtom>
        <TodoAtomList></TodoAtomList>
        <br />
        <br />
        <br />
        <h3>valtio</h3>
        <NewTodoV></NewTodoV>
        <TodoListV></TodoListV>
        <h3>valtio(optimize)</h3>
        <TodoListOpt></TodoListOpt>
        <br />
        <br />
        <br />
      </main>
    </>
  );
}
