import NewTodo from "@/components/zustand/NewTodo";
import TodoList from "@/components/zustand/TodoList";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3>Zustand</h3>
        <NewTodo></NewTodo>
        <TodoList></TodoList>
      </main>
    </>
  );
}
